{% extends "base.phtml" %}
{% block title%}Building{% endblock %}
{% block content %}
    <div class="ui container">
        <div class="ui segments">

            <div class="ui segment">
                <h3>[Building Name]</h3> <i>[R Icon, if reservation available]</i>
            </div>

            <div class="ui segment">
                [Building Gallery]
            </div>

            <div class="ui segment">
                [Amenities]
                [Description]
            </div>

            <div class="ui segment">
                [Floors]
            </div>

        </div>
    </div>
{% endblock %}