<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta charset='utf-8'>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="description" content="Executive Woocommerce">  

    <!--Semantic UI-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.13/semantic.min.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script  src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.13/semantic.min.js"></script>
    

    <link rel="stylesheet" href="https://afeld.github.io/emoji-css/emoji.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.1.4/Chart.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/javascript.util/0.12.12/javascript.util.min.js"></script>

    <!-- colors -->
    <link rel="stylesheet" href="css/base.css" />
  </head>
  <body>

    <style media="screen">
      .toggler {
        cursor: pointer;
      }
    </style>
    <script type="text/javascript">
      $(
        function() {
          $('#show-sidebar').click(
            function() {
              console.log("i'm clicking"); //I added semi-collon. Yet, I am not sure if it's necessary.
              $('#hamburger-button').removeClass('sidebar').addClass('sidebar');
              $('.menu.sidebar').sidebar('toggle');
            }
          );
          $('#hide-sidebar').click(function() {
            $('.menu.sidebar').sidebar('toggle');
            $('#hamburger-button').removeClass('cancel').addClass('sidebar');
          });
        }
      );
    </script>
  </head>
  <body >
    <!-- left -->
    <div class="ui left  vertical menu sidebar blue_back ">
      <div class="item">
        <div id="hide-sidebar" class="button">
           <strong>Menu</strong>
        </div>
      </div>
      <a class="item" href="/">
        Home<i class="home icon"></i> 
      </a>
      <!-- FILTER start
      <a class="item" href="/filter">
        Filter<i class="filter icon"></i>
      </a>
      FILTER end -->
      <a class="item" href="/support">
        Support<i class="life ring icon"></i>
      </a>
    </div>
    <div id="push" class="pusher" >


      <!-- top menu -->
      <div style=" width: 100%; height: 60px;" class="blue_back ui inverted vertical sticky fixed top white" >

        <!-- button -->
        <div id="show-sidebar" class="button toggler white" style="margin: 15px; display: inline-block;">
          <i id="hamburger-button" class="big sidebar inverted icon"></i>
        </div> 

        <!-- logo -->
        <div style="display:inline-block; margin-left:auto; margin-right:auto; top: 10px; position: relative; padding-right: 10px;">
          <a href="/"><img src="img/logo.png" style="margin" /></a>
        </div>  

        <!-- title -->
        <div style="display: inline-block; margin-left:auto; margin-right:auto; margin-bottom:10px; font-size: 20px;">
            <a href="/" style="text-decoration: none;">SpotFinder.tk</a>
        </div>



        <!-- campus -->
        <!-- still need to add icons of campuses -->
        <div class="ui floating labeled icon dropdown button" style="display: inline-block; margin-right: 0px; position: absolute; margin:12px; right:0px; background-color: #01573C;">
          <i class="marker icon"></i>
          <span class="text">Change campus</span>
          <div class="menu">
            <div class="header">
              Currently selected
            </div>
            <div class="item">
              <img class="ui avatar image" src="/images/avatar/small/jenny.jpg">
              California State University, Sacramento
            </div>
            <div class="divider"></div>
            
            <div class="header">
              List of campuses
            </div>

            <!-- TESTING area for campuses -->

            <div class="item">
              <img class="ui avatar image" src="/images/avatar/small/justen.jpg">
              American River College
            </div>
            <div class="item">
              <img class="ui avatar image" src="/images/avatar/small/christian.jpg">
              University of California, Berkeley
            </div>
            <div class="item">
              <img class="ui avatar image" src="/images/avatar/small/matt.jpg">
              University of California, Davis
            </div>
            



          </div>
        </div>
        <script>
          $(document).ready(
            function () {
              
            }
          );
      </script>
      </div>


      <div style="height: 75px">
      </div>
      <!-- Site content !-->
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>