{% extends "base.phtml" %}

{% block title%}Study{% endblock %}
{% block content %}
    <div class="ui container">

        <div class="ui segments">
            
            <div class="ui segment">
                <h3>Nearby Buildings</h3>
            </div>

            <div class="ui segment">
                <table class="ui celled unstackable table">
                    <tr>
                        <td>AIRC</td>
                        <td> <i class="blue lemon icon"></i> </td>
                    </tr>             
                    <tr>
                        <td>Library</td>
                        <td>5</td>
                    </tr>             
                    <tr><td>Building 1</td></tr>             
                    
                    <tr><td>Building 1</td></tr>             

                </table>
   

            </div>

        </div>
    
    </div>


{% endblock %}