<html>

<head>

</head>

<body>

    <?php 
        $title = "Home";
        include("base/menu.phtml");
    ?>


    <div class="ui container">

        <div class="ui segments">
            
            <div class="ui segment">
                <h3>Display info about nearby buildings</h3>
            </div>

            <div class="ui segment">
                <table class="ui celled unstackable table">
                    <tr><td>Building 1</td></tr>             
                    <tr><td>Building 1</td></tr>             
                    <tr><td>Building 1</td></tr>             
                    <tr><td>Building 1</td></tr>             
                    <tr><td>Building 1</td></tr>             
                    <tr><td>Building 1</td></tr>             
                    <tr><td>Building 1</td></tr>             
                    <tr><td>Building 1</td></tr>             

                </table>
   

            </div>

        </div>
    
    </div>
</body>






</html>