<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %}{% endblock %}</title>

    <!-- Meta Tags -->
    <meta charset='utf-8'>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="description" content="Executive Woocommerce">  

    <!--Semantic UI-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.13/semantic.min.css" />
      <!--JQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script  src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.13/semantic.min.js"></script>
    
    <!-- Other libraries -->
    <link rel="stylesheet" href="https://afeld.github.io/emoji-css/emoji.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.1.4/Chart.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/javascript.util/0.12.12/javascript.util.min.js"></script>

    <!-- CSS -->
    <link rel="stylesheet" href="css/base.css" />

    <!-- JavaScript -->
    <script type="text/javascript">
      $(
        function() {
          $('#show-sidebar').click(
            function() {
              console.log("i'm clicking");
              $('#hamburger-button').removeClass('sidebar').addClass('sidebar');
              $('.menu.sidebar').sidebar('toggle');
            }
          );
          $('#hide-sidebar').click(function() {
            $('.menu.sidebar').sidebar('toggle');
            $('#hamburger-button').removeClass('cancel').addClass('sidebar');
          });
        }
      );
    </script>
  </head>

  <body >
    <!-- side menu -->
    <div class="ui left  vertical menu sidebar blue_back ">
      <div class="item">
        <div id="hide-sidebar" class="button">
           <strong>Menu</strong>
        </div>
      </div>

      <a class="item" href="/">
        Find Spot<i class="search icon"></i> 
      </a>
      
      <a class="item" href="/account">
        My Account<i class="user icon"></i>
      </a>
      

      <a class="item" href="/support">
        Support<i class="life ring icon"></i>
      </a>

      <!-- visible only for users logged and as admin -->
      <a class="item" href="/admin">
        Administration Panel<i class="configure icon"></i>
      </a>


    </div>
    <div id="push" class="pusher" >


      <!-- top menu -->
      <div style=" width: 100%; height: 60px;" class="blue_back ui inverted vertical sticky fixed top white" >

        <!-- button -->
        <div id="show-sidebar" class="button toggler white" style="margin: 15px; display: inline-block;">
          <i id="hamburger-button" class="big sidebar inverted icon"></i>
        </div> 

        <!-- logo -->
        <div style="display:inline-block; margin-left:auto; margin-right:auto; top: 10px; position: relative; padding-right: 10px;">
          <a href="/"><img src="img/logo.png" style="margin" /></a>
        </div>  

        <!-- title -->
        <div style="display: inline-block; margin-left:auto; margin-right:auto; margin-bottom:10px; font-size: 20px;">
            <a href="/" style="text-decoration: none;">SpotFinder.tk</a>
        </div>



        <!-- campus -->
        <!-- still need to add icons of campuses -->
        <div class="ui floating labeled icon dropdown button" style="display: inline-block; margin-right: 0px; position: absolute; margin:12px; right:0px; background-color: white;">
          <i class="marker icon"></i>
          <span class="text">Change campus</span>
          <div class="menu">
            <div class="header">
              Currently selected
            </div>
            <div class="item">
              <img class="ui avatar image" src="/images/avatar/small/jenny.jpg">
              {% for campus in campuses %}
                {% if campus.idcampus == campusSelected %}
                  {{ campus.name }}
                {% endif %}
              {% endfor %}
            </div>
            <div class="divider"></div>
            
            <div class="header">
              List of campuses
            </div>

            {% for campus in campuses %}
            <!-- a tags should be outside of the divs, but the CSS has to be modified first so that it displays correctly.
              Else, the user doesn't get redirected unless the words are clicked -->
            <div class="item" href="{{ page }}?campusSelected={{ campus.idcampus }}" style="color: black;">
              <img class="ui avatar image" src="/images/avatar/small/justen.jpg">
              <a style="color:black;">{{ campus.name }}</a>
            </div>
            {% endfor %}
            

          </div>
        </div>


        <!-- Script so that the Change Campus menu works -->
        <script>
          $(document).ready(
            function () {
              $('.ui.dropdown')
                .dropdown(

                )
              ;
            }
          );
      </script>
      </div>


      <div style="height: 75px">
      </div>
      <!-- Site content !-->
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>