{% extends "base.phtml" %}
{% block title%}Study{% endblock %}
{% block content %}
    <div class="ui container">
        <div class="ui segments">
            <div class="ui segment">
                <h3>AIRC</h3>
            </div>
            <div class="ui segment">
                <table class="ui celled unstackable table">
                    <tr>
                        <td>FLOOR 1 &#x2665;</td>
                        <td><i style="font-size: 40px" class="em em-thumbsup"></i></td>
                        <td><button class="ui button">Update</button></td>
                    </tr>             
                    <tr>
                        <td>FLOOR 2</td>
                        <td><i style="font-size: 40px" class="em em-smile"></i></td>
                        <td><button class="ui button">Update</button></td>
                    </tr>  
                </table>
            </div>
            <div class="ui segment">
            </div>
        </div>
    </div>
{% endblock %}