{% extends "base.phtml" %}
{% block title%}Building{% endblock %}
{% block content %}
    <div class="ui container">
        <div class="ui segments">

            <div class="ui segment">
                <h3>Building name</h3> <i>Icon of R if reserved available</i>
            </div>

            <div class="ui segment">
                pics here
            </div>

            <div class="ui segment">
                amenities and description here
            </div>

            <div class="ui segment">
                floors here
            </div>

        </div>
    </div>
{% endblock %}