<html>
<head>
</head>
<body>
   <?php 
      $title = "Filter";
      include("menu.phtml");
      ?>
   <div class="ui container">
      <div class="ui segments">



         <div class="ui segment">
            <div class="ui checkbox">
               <input type="checkbox" name="example">
               <label>AMENITY</label>
            </div>
            <div class="ui checkbox">
               <input type="checkbox" name="example">
               <label>AMENITY</label>
            </div>
         </div>
      </div>
      <div class="ui segment">
            <div class="ui checkbox">
               <input type="checkbox" name="example">
               <label>AMENITY</label>
            </div>
            <div class="ui checkbox">
               <input type="checkbox" name="example">
               <label>AMENITY</label>
            </div>
         </div>
      </div>

      <div class="ui segment">
      <button style="float: center;" class="ui large blue button">Filter</button></div>



   </div>
   </div>
</body>
</html>