{% extends "base.phtml" %}
{% block title%}Study{% endblock %}
{% block content %}
    <div class="ui container">
        <div class="ui segments">
            <div class="ui segment">
                <h3>Building name</h3>
            </div>

            <div class="ui segment">
                <h3>floor name/number</h3> <i>Icon of R if reserved available</i>
            </div>

            <div class="ui segment">
                status bar, amenities and description here
            </div>

            <div class="ui segment">
                rooms here with indications of "if ocuppied or not"
            </div>

        </div>
    </div>
{% endblock %}