
<html>

<head>

</head>

<body>
<?php 
        
        $title = "Status";
        include("menu.phtml");
?>



<div class="ui container">
<table class="ui celled unstackable table">

    <tr>
    <thead>
        <tr>
            <th>Room</th>
            <th>Busy?</th>
            <th>etc.</th>
        </tr>

    </thead>
    <tr>
            
        <td>Room 1</td>
        <td>Yes</td>
        <td>...</td>
    </tr>
    <tr>
            
        <td>Room 1</td>
        <td>Yes</td>
        <td>...</td>
    </tr>
    <tr>
            
        <td>Room 1</td>
        <td>Yes</td>
        <td>...</td>
    </tr>
    <tr>
            
        <td>Room 1</td>
        <td>Yes</td>
        <td>...</td>
    </tr>
    <tr>
            
        <td>Room 1</td>
        <td>Yes</td>
        <td>...</td>
    </tr>        
    </tr>
</table>
</div>






</body>
</html>