<html>
<head>
</head>
<body>
   <?php 
      $title = "Filter";
      include("menu.phtml");
      ?>
   <div class="ui container">
      <div class="ui segments">
    <div class="ui segment">
        <h3>Submit data for: Example Room</h3>
    </div>
    <div class="ui segment">
 

      <button class="ui red button">Full</button>


    <button class="ui yellow button">Limited</button>
    


    <button class="ui green button">Very Open</button>




     
    </div>

 

      <div class="ui segment">
      <button style="float: center;" class="ui large blue button">Submit</button>
      </div>



   </div>
   </div>
</body>
</html>