{% extends "base.phtml" %}
{% block title%}404 Error - Not Found{% endblock %}
{% block content %}
    <div class="ui container">
        <div class="ui segments">






            <div class="ui segment">
                <h3>This is Taras Sectgio!!!!!!!!</h3> <i>Icon of R if reserved available</i>
            </div>
            <div class="ui segment">
                <h3>This section is done by: Tara Ross Alias 'Taras Sectgio'</h3> <i>Icon of R if reserved available</i>
            </div>
            <div class="ui segment">
                <h3>Nick: here, this is my life</h3> <i>Thug life</i>
            </div>






        </div>
    </div>
{% endblock %}